### Test Serve Dir
GET http://127.0.0.1:8080/tower/Cargo.toml HTTP/2

### Test Serve Dir Not Found
GET http://127.0.0.1:8080/tower/Unknown HTTP/2

### Test Origin File
GET http://127.0.0.1:8080/origin/Cargo.toml HTTP/2

### Test Origin Dir With Index.html
GET http://127.0.0.1:8080/origin/fixtures/ HTTP/2

### Test Origin Root Dir With Index.html
GET http://127.0.0.1:8080/origin HTTP/2

### Test Origin Dir Not Found
GET http://127.0.0.1:8080/origin/Unknown HTTP/2
